### ISSUE TITLE
Remove `tar.gz` dependency

### ISSUE THREAD

**Issue by icaroharry** [MaiaVictor/swarm-js#10]
When installing web3.js I'm getting: `npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar`

According to its [repo](https://github.com/alanhoff/node-tar.gz). Tar.gz it's not maintained anymore.

**Comment by sgehrman** [comment]
I'm getting this.

npm ERR! missing: tar.gz@^1.0.5, required by swarm-js@0.1.37

How do I fix this?

**Comment by INTERESTING-OMG** [comment]
I have the same question

**Comment by JirkaChadima** [comment]
This is already done in #12, @evertonfraga Can you merge it?
