### ISSUE TITLE
The following leaks were detected:@@any-promise/REGISTRATION

### ISSUE THREAD

**Issue by vforv** [MaiaVictor/swarm-js#15]
When I try to test my code I get an error in the title...

Can you remove that pkg(fs-promise) from swarm-js or remove any-promise from other pkgs?

```
└─┬ web3-js@1.0.0-beta.26
  └─┬ web3-bzz@1.0.0-beta.26
    └─┬ swarm-js@0.1.37
      └─┬ fs-promise@2.0.3
        ├── any-promise@1.3.0 
        ├─┬ mz@2.7.0
        │ └── any-promise@1.3.0  deduped
        └─┬ thenify-all@1.6.0
          └─┬ thenify@3.3.0
            └── any-promise@1.3.0  deduped

```

**Comment by lukehedger** [comment]
There is already an open PR to remove this package - https://github.com/MaiaVictor/swarm-js/pull/13

**Comment by evertonfraga** [comment]
That was removed in #13 and #24. Sorry it took long. Please let me know if you hit another roadbump.
