### ISSUE TITLE
Implement URI scheme updates

### ISSUE THREAD

**Issue by lukehedger** [MaiaVictor/swarm-js#17]
The `bzzr` URI scheme has been [deprecated in favour of `bzz-raw`](https://github.com/ethereum/go-ethereum/pull/15667).

`bzzr` is still supported for now but an upgrade path to implement `bzz-raw` should be considered.

As not all consumers of the `swarm-js` library will use Swarm/Geth ^1.8.0, use of the `bzzr` scheme cannot simply be replaced with `bzz-raw`. Perhaps the scheme update should be made in a major release and documented in the readme.

@MaiaVictor - What are your thoughts?

**Comment by JirkaChadima** [comment]
Is there anything going on with this, @evertonfraga? I'll be happy to submit a PR.

**Comment by evertonfraga** [comment]
@JirkaChadima greatly appreciated! I got caught in a release on another project I work and couldn't tackle the schema change.
