### ISSUE TITLE
add your `.babelrc` file to you ``.npmignore`` file

### ISSUE THREAD

**Issue by ortonomy** [MaiaVictor/swarm-js#21]
Would you consider adding your ``.babelrc`` to your ``.npmignore`` file? Relevant to this issue [here](https://github.com/reflux/reflux-core/pull/32):

> your .babelrc is breaking my react-native project [facebook/react-native#8296](https://github.com/facebook/react-native/issues/8296). Please consider ignoring your .babelrc file as I don't believe you need it in your npm module. 

Trying to use web3.js in react-native and get an error because of your presets. I have had to add the module just to get it to work.

**Comment by evertonfraga** [comment]
I am now using the recommended setup for Babel 7 (v0.1.39). That'll probably do the job. 

Please let me know otherwise.
