### ISSUE TITLE
deprecated warning from npm install

### ISSUE THREAD

**Issue by judyyang40** [MaiaVictor/swarm-js#23]
Hi,
I'm still receiving the following warning, probably because web3 submodule has swarm-js as a dependency:
fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
I see that a PR was merged to fix this issue?

**Comment by evertonfraga** [comment]
The fix is in place. Please use 0.1.38 and let me know of any further inconvenience.
