### ISSUE TITLE
Module not found: Error: Can't resolve 'child_process' in swarm-js/lib

### ISSUE THREAD

**Issue by niksmac** [MaiaVictor/swarm-js#6]
Module not found: Error: Can't resolve 'child_process' in '/Users/niksair/iWork/projects/youribot/newui/node_modules/web3/packages/web3-bzz/node_modules/swarm-js/lib'

**Comment by christopherdro** [comment]
Related https://github.com/ethereum/web3.js/issues/923

**Comment by MaiaVictor** [comment]
I'm not familiar with webpack, but my guess is that line 275:

    const {spawn} = require("c"+"hild_process");

Which is an ugly hack to hide that import from `browserify` is actually understood by webpack. I'm not sure what is the proper way to import a library on Node.js, while still ignoring it on the browser for both webpack and browserify. Could someone link me to the proper way to do it?

**Comment by christopherdro** [comment]
Update:

<img width="1080" alt="screen shot 2017-07-26 at 9 16 35 pm" src="https://user-images.githubusercontent.com/3741055/28654264-d216718a-7247-11e7-896d-096157de475a.png">

**Comment by christopherdro** [comment]
It appears https://www.npmjs.com/package/mime-types allow builds to pass. Not sure if the API matches one to one but might be a possible swap. Looks like it's being actively maintained as well.
